language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_install: sudo bash -c 'echo "87.98.253.108 getcomposer.org" >> /etc/hosts' 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
